baseurl: https://blog.smallten.me/
languageCode: en-us
title: 小十的部落格
theme: hugo-theme-stack

services:
    googleAnalytics:
        ID: G-9L51K4B2CR

sitemap:
    changefreq: monthly
    filename: sitemap.xml
    priority: 0.5

permalinks:
    post: /p/:slug/
    page: /:slug/

enableEmoji: true

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: /image/favicon.png

    footer:
        since: 2020
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji:
        subtitle: 教學、資訊分享、生活記趣
        avatar:
            enabled: true
            local: true
            src: img/avatar.png

    article:
        headingAnchor: true
        math: true
        readingTime: true

    widgets:
        homepage: [
            {
                type: "archives",
                params.limit: 5
            },
            {
                type: "tag-cloud",
                params.limit: 20
            }
        ]
        page: [
            type: "toc"
        ]

    colorScheme:
        toggle: true
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          params:
              icon: home
    
        - identifier: about
          name: About
          url: /about
          weight: -90
          params:
              icon: user

        - identifier: archives
          name: Archives
          url: /archives
          weight: -70
          params:
              icon: archives

        - identifier: search
          name: Search
          url: /search
          weight: -60
          params:
              icon: search

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/Adam7066
          params:
              icon: brand-github

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: true
    tableOfContents:
        ordered: false
        startLevel: 1
        endLevel: 3
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4
